version: '3.1'
services:
  database:
    container_name: cv_database
    image: postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: cv_db
    ports:
      - "5432:5432"
